[package]
name = "splitter"
version = "0.1.0"
authors = ["Jonathan <jonathanwoollettlight@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image=  "0.22.3"    # Image manipulation
itertools = "0.8.2"